### ISSUE TITLE
Is there any way I can access to blob or chunk in real time?

### ISSUE THREAD

**Issue by ohtangza** [agrasley/react-recorder-redux#1]
I am developing real-time audio stream application. Is there any way I can access to the buffer in real time? Or at least any way to create blob while recording?

**Comment by val-grasley** [comment]
You'll have to describe more about your use case. If all you need is real-time access to the audio stream, then you just need the stream object returned by this component, bypassing the Blob object entirely. If you need real-time access to the Blob object itself, then it gets a little trickier. Give me an idea of what you want to do with the audio once you've got it and I can maybe help point you in the right direction.

**Comment by val-grasley** [comment]
Closing this unless there's further questions.

**Comment by ohtangza** [comment]
I was trying to connect this components to IBM watson speech reocognition service with WebSocket. Thanks for your answer, I'll try to use the stream returned by the component.
