### ISSUE TITLE
recorder stop is not executed

### ISSUE THREAD

**Issue by whiteadi** [agrasley/react-recorder-redux#2]
Hi,

I debugged and it does not ever comes into the react-recorder stop function if you dispatch the @@react-recorder/STOP action calling recorderStop.
Regards,
Adrian

**Comment by val-grasley** [comment]
It works in the demo and passes the proper tests: https://agrasley.github.io/react-audio-example/. You'll have to give me more information.

**Comment by whiteadi** [comment]
Hi,

and thanks for reply,

it does stop the drawing (VolumeMeter) but not the recording or at least I cannot see it going into rect-recorder stop method and anyway more important the recording icon is on, please check yourself when pressing stop if it disappear, check also my attached screenshot.
![screen shot 2017-01-20 at 08 39 48](https://cloud.githubusercontent.com/assets/4496789/22140466/fb8f4a44-deec-11e6-9e8b-02785c4079ef.png)

**Comment by val-grasley** [comment]
This is actually a browser-level issue. The recording indicator doesn't go away even when the recording is technically stopped. As long as you're using the `getUserMedia` API call, the recording icon is visible in the browser tab, even if you're not actually doing anything with that recording object. So the recording process does in fact stop, it just doesn't make the indicator go away.

**Comment by whiteadi** [comment]
Well if this is the browser then indeed nothing can be done. (Strange that I debugged it and it didn't seem to go to the react-recorder component's stop method.) Thank you for the help!

**Comment by KaptenJansson** [comment]
That is not correct, the recording indicator should stop when all the tracks have been stopped. You are correct in that when getUserMedia has been requested on a page that an indicator remains however it's not the recording indicator, its the camera icon to the right in the URL bar.

I cannot reproduce this issue in Chrome, I suspect it's the react library not doing the right thing as indicated in @whiteadi's comment.

**Comment by val-grasley** [comment]
When I run it in the debugger it shows that the state of the MediaRecorder switches from "recording" to "inactive" when I call MediaRecorder.stop(). Do I need some additional behavior?

**Comment by whiteadi** [comment]
I also debugged it but it didn't go there to actually call the stop on the MediaRecorder, I end up using: https://webrtc.github.io/samples/src/content/getusermedia/volume/

Thanks anyway ;)

**Comment by KaptenJansson** [comment]
@agrasley do you have any mediaStreams left alive?
